name: gwb-dc

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - mkl
  - dask
  - zarr
  - sparse
  - discretize
  - pip:
    - git+https://github.com/simpeg/simpeg.git@simulation_DC2.5DSpeedup
    - empymod
